### ISSUE TITLE
[feature request] Click after refresh

### ISSUE THREAD

**Issue by shucksys** [Akenaide/bako#5]
Hello there

Would it be possible to implement a listener to click on the loading screen or the Full Auto/Semi Auto button after refreshing attack? 

Essentially this would create a seemless loop with FA/SA but with refreshes, however it is possible that this becomes detectable/bannable as it is close to automation.

Merci beaucoup :)

**Comment by Akenaide** [comment]
Hello,

I got the same idea years ago, but I decided to avoid everything about interaction with the windows. I don't know how good is the "bot detection".

Well you can fork it to implement it and I can help if you need some help.
